export const getToken = () => {
    return "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InByb2ZpbGUiOnsicHJpdmF0ZURlY2tzIjpbXSwicmV2aWV3ZWREZWNrcyI6W10sInVzZXJuYW1lIjoidGVzdCJ9LCJlbWFpbCI6InVzZXIudGVzdEB0ZXN0LmNvbSJ9LCJpYXQiOjE2MjcxMzk4ODUsImV4cCI6MTYyNzE0MzQ4NX0.MU1a-voNe2mAEemQHuDNfTidfDwwCIGkzpi1wOJIjao";
};
